ip.address=127.0.0.1
port.number=4723
appium.main.js=C://Users//shady gamal//AppData//Roaming//npm//node_modules//appium//build//lib//main.js
app.path=C://Users//shady gamal//IdeaProjects//AppiumFramework//resources//ApiDemos-debug.apk
device.name=R52N91767XX
platform.name=Android
automation.name=UiAutomator2